apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.name }}
  labels: 
    entity-id: ${{values.name}}
    app: ${{values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
  template:
    metadata:
      labels:
        backstage.io/kubernetes-id: ${{ values.name }}
        entity-id: ${{values.name}}
        app: ${{ values.name }}
    spec:
      serviceAccountName: ${{ values.name }}
      containers:
      - name: ${{ values.name }}
        image: ${{ values.owner }}/${{ values.name }}:0.1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"  
            cpu: "200m"       
          requests:
            memory: "128Mi"  
            cpu: "100m"      
