---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: This is a basic Go application
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'entity-id=${{values.name}}'
    backstage.io/kubernetes-namespace: ${{values.name}}
    argocd/app-name: ${{values.name | dump}}
  links:
    - url: https://github.com/${{values.owner | dump}}/${{values.name | dump}}
      title: Repo URL
      icon: github
spec:
  owner: platform
  lifecycle: experimental
  type: service
  system: ${{values.name | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{values.name | dump}}
  description: An example system for demonstration purposes
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/dgeorgievski/backstage-templates
      title: Template Repo
      icon: github
spec:
  owner: platform
  lifecycle: experimental
  type: service
